export const BCRYPT_SALT_ROUNDS = 10;
export const DEFAULT_PAGE_SIZE = 10;
export const MAX_PAGE_SIZE = 100;
export const CURRENT_TIMESTAMP = 'CURRENT_TIMESTAMP(6)';

export const STATUS_ACTIVE = 'active';
export const STATUS_BLOCKED = 'blocked';
export const STATUS_INACTIVE = 'inactive';

export const STATUSES = {
  ACTIVE: STATUS_ACTIVE,
  INACTIVE: STATUS_INACTIVE,
  BLOCKED: STATUS_BLOCKED
};

export const REGISTRATION_STATUS_NEW = 'New';
export const REGISTRATION_STATUS_INCOMPLETE = 'Incomplete';
export const REGISTRATION_STATUS_PENDING = 'Pending';
export const REGISTRATION_STATUS_APPROVAL = 'Approval';
export const REGISTRATION_STATUS_REGISTERED = 'Registered';

export const REGISTRATION_STATUSES = {
  NEW: REGISTRATION_STATUS_NEW,
  INCOMPLETE: REGISTRATION_STATUS_INCOMPLETE,
  PENDING: REGISTRATION_STATUS_PENDING,
  APPROVAL: REGISTRATION_STATUS_APPROVAL,
  REGISTERED: REGISTRATION_STATUS_REGISTERED
};
